name: 'Lint & Test'
on:
- push
jobs:
  Lint-and-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up Poetry
        run: pipx install "poetry==1.8.3"
      - name: Set up project
        run: poetry install
      - name: Lint
        run: |
          poetry run toml-sort --check pyproject.toml
          poetry run isort --check tests
          poetry run black --check tests
          poetry run mypy tests
      - name: Test
        run: poetry run pytest tests
