# See:
# https://github.com/actions/starter-workflows/blob/main/pages/static.yml
# https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages#linking-separate-build-and-deploy-jobs
name: Deploy Site

on:
  push:
    branches:
    - doc/gh-pages  # Change to main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Lint-and-Test:
    uses: ./.github/workflows/lint-test.yaml
  Build-site:
    runs-on: ubuntu-latest
    needs: Lint-and-Test
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up poetry
      run: pipx install "poetry==1.8.3"
    - name: Set up project
      run: poetry install
    - name: Build site
      run: mkdocs build --site-dir ./site
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./site
  Deploy-site:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: Build-site
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
